### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by 4taa** [Artefakt-ff/js-course-zero-task#2]
`"use strict";`
`// Было бы круто, если бы прочитал про` `https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Functions/Arrow_functions`
`// заодно напиши JSDoc, так как js нетипизированный язык, а дока позволяет лучше понимать функционал функции:)`
`const chess = function (size) {`
`    if (isNaN(parseInt(size))) // Почему бы не сделать typeof size !== 'Number'`
`        return null;`

`    if (size < 2)`
`        return null; // ifelse с одной записью принято писать в одну строку; почему бы не` `объединить два if в один?`

`    let row = "", board = "", flag = 1, row_truncated; // по кодстайлу принято использовать` `одинарные кавычки`
`    for (let i = 0; i < size / 2 + 1; i++) {`
`        row += "* ";`
`    }`
`    row = row.substring(0, size);`
`    row_truncated = row.substring(0, size - 1); // опять же кодстайл тут пишетсяВотТакВот :)`
`    for (let i = 0; i < size; i++) {`
`        if (flag === 1) { // давай воспользуемся тернарным оператором?`
`            board += row + "\n";`
`        } else {`
`            board += " " + row_truncated + "\n"`
`        }`
`        flag *= -1;`
`    }`
`    return board;`
`}; // в конце файла принято оставлять пустую строку :)`

**Comment by Artefakt-ff** [comment]
Все исправил)
